name: Build and Commit Tokens

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install sass

      - name: Generate SCSS Partials and JSON
        run: node scripts/build-tokens.js

      - name: Compile Final tokens.css
        run: npx sass packages/tokens/tokens.scss packages/tokens/dist/tokens.css --no-source-map

      # ✅ CORRECTED: Use a single commit step at the end
      - name: Commit All Generated Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(tokens): build and commit latest tokens"
          # This pattern tells the action to commit all changes within
          # both the src and dist directories of the tokens package.
          file_pattern: "packages/tokens/ packages/tokens/dist/"
